FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install hazelcast-python-client==5.3.0

COPY . .

EXPOSE ${PORT:-8081}

CMD ["python", "-m", "planning_service.main"]
