FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install hazelcast-python-client==5.3.0

COPY . .

EXPOSE ${6101:-6101}

CMD python -m communication_service.main 1
