### Add User
POST http://localhost:8000/api/v1/user_management_service/add_user
Content-Type: application/json

{
  "user_name": "test_user_2",
  "password": "password",
  "email": "pelehbog@gmail.com"
}



### Authenticate User
GET http://localhost:8000/api/v1/user_management_service/authenticate
Content-Type: application/json

{
  "user_name": "test_user_2",
  "password": "password"
}

### Create Group
POST http://localhost:8000/api/v1/user_management_service/create_group
Content-Type: application/json

{
  "user_token": "74c521da-70c4-4425-8ffe-fe12d843d3b0",
  "group_name": "New_Group_1",
  "users_list": [
    "test_user_2"
  ]
}

### Add User to Group
POST http://localhost:8000/api/v1/user_management_service/add_user_to_group
Content-Type: application/json

{
  "group_token": "b02e2ea0-2ebc-4e55-aaee-f58593a99044",
  "user_name": "test_user_3",
  "user_token": "c4691cba-0754-400c-9488-4b323b8ef44c"
}

### Delete User from Group
POST http://localhost:8000/api/v1/user_management_service/delete_user_from_group
Content-Type: application/json

{
  "group_token": "dfdfefa0-a8e0-4ab2-8e7a-b816eec8b41c",
  "user_name": "test_user_3",
  "user_token": "c4691cba-0754-400c-9488-4b323b8ef44c"
}

### Delete Group
DELETE http://localhost:8000/api/v1/user_management_service/delete_group
Content-Type: application/json

{
  "group_token": "dfdfefa0-a8e0-4ab2-8e7a-b816eec8b41c",
  "user_token": "c4691cba-0754-400c-9488-4b323b8ef44c"
}

### Delete User
DELETE http://localhost:8000/api/v1/user_management_service/delete_user
Content-Type: application/json

{
  "user_token": "1c19e942-253b-4163-b2f5-d4355b03741a"
}

### Get Group Users
GET http://localhost:8000/api/v1/user_management_service/get_group_users
Content-Type: application/json

{
  "group_token": "dfdfefa0-a8e0-4ab2-8e7a-b816eec8b41c"
}

### Check User Existence
GET http://localhost:8000/api/v1/user_management_service/user_existance
Content-Type: application/json

{
  "user_name": "test_user_2"
}
